{
 "title": "Mysql dashboard",
 "description": "DDoS Test",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Mysql data in total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_global_status_bytes_sent", "legendFormat": "Data Sent" },
    {
     "expr": "mysql_global_status_bytes_received",
     "legendFormat": "Data Received"
    }
   ]
  },
  {
   "title": "InnoDB data in total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_data_written",
     "legendFormat": "Data Write"
    },
    {
     "expr": "mysql_global_status_innodb_data_read",
     "legendFormat": "Data Read"
    }
   ]
  },
  {
   "title": "Number of connections ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_connections",
     "legendFormat": "Total"
    },
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "Active Connection"
    }
   ]
  },
  {
   "title": "Number of threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_created",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}